// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include "cpp_features.hpp"

#if REX_HAS_CONSTEXPR || defined(REX_DOC_BUILD)
	#define REX_CONSTEXPR constexpr
	#define REX_CONST_CONSTEXPR constexpr
	#define REX_INLINE_CONSTEXPR constexpr
	#define REX_INLINE_CONST_CONSTEXPR constexpr
#else
	#define REX_CONSTEXPR
	#define REX_CONST_CONSTEXPR const
	#define REX_INLINE_CONSTEXPR inline
	#define REX_INLINE_CONST_CONSTEXPR inline const
#endif

#if REX_HAS_IF_CONSTEXPR
	#define REX_IF_CONSTEXPR REX_CONSTEXPR
#else
	#define REX_IF_CONSTEXPR
#endif

// C++11
#if REX_HAS_CPP11
	#define REX_CONSTEXPR_CPP11 REX_CONSTEXPR
	#define REX_CONST_CONSTEXPR_CPP11 REX_CONST_CONSTEXPR
	#define REX_INLINE_CONSTEXPR_CPP11 REX_INLINE_CONSTEXPR
	#define REX_INLINE_CONST_CONSTEXPR_CPP11 REX_INLINE_CONST_CONSTEXPR
#else
	#define REX_CONSTEXPR_CPP11
	#define REX_CONST_CONSTEXPR_CPP11 const
	#define REX_INLINE_CONSTEXPR_CPP11 inline
	#define REX_INLINE_CONST_CONSTEXPR_CPP11 inline const
#endif

// C++14
#if REX_HAS_CPP14
	#define REX_CONSTEXPR_CPP14 REX_CONSTEXPR
	#define REX_CONST_CONSTEXPR_CPP14 REX_CONST_CONSTEXPR
	#define REX_INLINE_CONSTEXPR_CPP14 REX_INLINE_CONSTEXPR
	#define REX_INLINE_CONST_CONSTEXPR_CPP14 REX_INLINE_CONST_CONSTEXPR
#else
	#define REX_CONSTEXPR_CPP14
	#define REX_CONST_CONSTEXPR_CPP14 const
	#define REX_INLINE_CONSTEXPR_CPP14 inline
	#define REX_INLINE_CONST_CONSTEXPR_CPP14 inline const
#endif

// C++17
#if REX_HAS_CPP17
	#define REX_CONSTEXPR_CPP17 REX_CONSTEXPR
	#define REX_CONST_CONSTEXPR_CPP17 REX_CONST_CONSTEXPR
	#define REX_INLINE_CONSTEXPR_CPP17 REX_INLINE_CONSTEXPR
	#define REX_INLINE_CONST_CONSTEXPR_CPP17 REX_INLINE_CONST_CONSTEXPR
#else
	#define REX_CONSTEXPR_CPP17
	#define REX_CONST_CONSTEXPR_CPP17 const
	#define REX_INLINE_CONSTEXPR_CPP17 inline
	#define REX_INLINE_CONST_CONSTEXPR_CPP17 inline const
#endif

// C++20
#if REX_HAS_CPP20
	#define REX_CONSTEXPR_CPP20 REX_CONSTEXPR
	#define REX_CONST_CONSTEXPR_CPP20 REX_CONST_CONSTEXPR
	#define REX_INLINE_CONSTEXPR_CPP20 REX_INLINE_CONSTEXPR
	#define REX_INLINE_CONST_CONSTEXPR_CPP20 REX_INLINE_CONST_CONSTEXPR
#else
	#define REX_CONSTEXPR_CPP20
	#define REX_CONST_CONSTEXPR_CPP20 const
	#define REX_INLINE_CONSTEXPR_CPP20 inline
	#define REX_INLINE_CONST_CONSTEXPR_CPP20 inline const
#endif

// C++23
#if REX_HAS_CPP23
	#define REX_CONSTEXPR_CPP23 REX_CONSTEXPR
	#define REX_CONST_CONSTEXPR_CPP23 REX_CONST_CONSTEXPR
	#define REX_INLINE_CONSTEXPR_CPP23 REX_INLINE_CONSTEXPR
	#define REX_INLINE_CONST_CONSTEXPR_CPP23 REX_INLINE_CONST_CONSTEXPR
#else
	#define REX_CONSTEXPR_CPP23
	#define REX_CONST_CONSTEXPR_CPP23 const
	#define REX_INLINE_CONSTEXPR_CPP23 inline
	#define REX_INLINE_CONST_CONSTEXPR_CPP23 inline const
#endif
