// SPDX-License-Identifier: GPL-3.0-only

#pragma once

/**
 * @def REX_CPLUSPLUS
 * @brief C++ standard version
 * 
 */
#if defined(_MSVC_LANG)
# define REX_CPLUSPLUS (_MSVC_LANG)
#else
# define REX_CPLUSPLUS (__cplusplus)
#endif

#define REX_CPLUSPLUS11 (201103L)
#define REX_CPLUSPLUS14 (201402L)
#define REX_CPLUSPLUS17 (201703L)
#define REX_CPLUSPLUS20 (202002L)
#define REX_CPLUSPLUS23 (999999L) /*TBD*/

#define REX_HAS_CPP11 (REX_CPLUSPLUS >= REX_CPLUSPLUS11)
#define REX_HAS_CPP14 (REX_CPLUSPLUS >= REX_CPLUSPLUS14)
#define REX_HAS_CPP17 (REX_CPLUSPLUS >= REX_CPLUSPLUS17)
#define REX_HAS_CPP20 (REX_CPLUSPLUS >= REX_CPLUSPLUS20)
#define REX_HAS_CPP23 (REX_CPLUSPLUS >= REX_CPLUSPLUS23)
