// SPDX-License-Identifier: GPL-3.0-only

#pragma once

#include "cpp_features.hpp"

#if REXLIB_HAS_CONSTEXPR || defined(REXLIB_DOC_BUILD)
	#define REXLIB_CONSTEXPR constexpr
	#define REXLIB_CONST_CONSTEXPR constexpr
	#define REXLIB_INLINE_CONSTEXPR constexpr
	#define REXLIB_INLINE_CONST_CONSTEXPR constexpr
#else
	#define REXLIB_CONSTEXPR
	#define REXLIB_CONST_CONSTEXPR const
	#define REXLIB_INLINE_CONSTEXPR inline
	#define REXLIB_INLINE_CONST_CONSTEXPR inline const
#endif

#if REXLIB_HAS_IF_CONSTEXPR
	#define REXLIB_IF_CONSTEXPR REXLIB_CONSTEXPR
#else
	#define REXLIB_IF_CONSTEXPR
#endif

// C++11
#if REXLIB_HAS_CPP11
	#define REXLIB_CONSTEXPR_CPP11 REXLIB_CONSTEXPR
	#define REXLIB_CONST_CONSTEXPR_CPP11 REXLIB_CONST_CONSTEXPR
	#define REXLIB_INLINE_CONSTEXPR_CPP11 REXLIB_INLINE_CONSTEXPR
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP11 REXLIB_INLINE_CONST_CONSTEXPR
#else
	#define REXLIB_CONSTEXPR_CPP11
	#define REXLIB_CONST_CONSTEXPR_CPP11 const
	#define REXLIB_INLINE_CONSTEXPR_CPP11 inline
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP11 inline const
#endif

// C++14
#if REXLIB_HAS_CPP14
	#define REXLIB_CONSTEXPR_CPP14 REXLIB_CONSTEXPR
	#define REXLIB_CONST_CONSTEXPR_CPP14 REXLIB_CONST_CONSTEXPR
	#define REXLIB_INLINE_CONSTEXPR_CPP14 REXLIB_INLINE_CONSTEXPR
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP14 REXLIB_INLINE_CONST_CONSTEXPR
#else
	#define REXLIB_CONSTEXPR_CPP14
	#define REXLIB_CONST_CONSTEXPR_CPP14 const
	#define REXLIB_INLINE_CONSTEXPR_CPP14 inline
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP14 inline const
#endif

// C++17
#if REXLIB_HAS_CPP17
	#define REXLIB_CONSTEXPR_CPP17 REXLIB_CONSTEXPR
	#define REXLIB_CONST_CONSTEXPR_CPP17 REXLIB_CONST_CONSTEXPR
	#define REXLIB_INLINE_CONSTEXPR_CPP17 REXLIB_INLINE_CONSTEXPR
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP17 REXLIB_INLINE_CONST_CONSTEXPR
#else
	#define REXLIB_CONSTEXPR_CPP17
	#define REXLIB_CONST_CONSTEXPR_CPP17 const
	#define REXLIB_INLINE_CONSTEXPR_CPP17 inline
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP17 inline const
#endif

// C++20
#if REXLIB_HAS_CPP20
	#define REXLIB_CONSTEXPR_CPP20 REXLIB_CONSTEXPR
	#define REXLIB_CONST_CONSTEXPR_CPP20 REXLIB_CONST_CONSTEXPR
	#define REXLIB_INLINE_CONSTEXPR_CPP20 REXLIB_INLINE_CONSTEXPR
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP20 REXLIB_INLINE_CONST_CONSTEXPR
#else
	#define REXLIB_CONSTEXPR_CPP20
	#define REXLIB_CONST_CONSTEXPR_CPP20 const
	#define REXLIB_INLINE_CONSTEXPR_CPP20 inline
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP20 inline const
#endif

// C++23
#if REXLIB_HAS_CPP23
	#define REXLIB_CONSTEXPR_CPP23 REXLIB_CONSTEXPR
	#define REXLIB_CONST_CONSTEXPR_CPP23 REXLIB_CONST_CONSTEXPR
	#define REXLIB_INLINE_CONSTEXPR_CPP23 REXLIB_INLINE_CONSTEXPR
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP23 REXLIB_INLINE_CONST_CONSTEXPR
#else
	#define REXLIB_CONSTEXPR_CPP23
	#define REXLIB_CONST_CONSTEXPR_CPP23 const
	#define REXLIB_INLINE_CONSTEXPR_CPP23 inline
	#define REXLIB_INLINE_CONST_CONSTEXPR_CPP23 inline const
#endif
