// SPDX-License-Identifier: GPL-3.0-only

#pragma once

/**
 * @def REXLIB_CPLUSPLUS
 * @brief C++ standard version
 * 
 */
#if defined(_MSVC_LANG)
# define REXLIB_CPLUSPLUS (_MSVC_LANG)
#else
# define REXLIB_CPLUSPLUS (__cplusplus)
#endif

#define REXLIB_CPLUSPLUS11 (201103L)
#define REXLIB_CPLUSPLUS14 (201402L)
#define REXLIB_CPLUSPLUS17 (201703L)
#define REXLIB_CPLUSPLUS20 (202002L)
#define REXLIB_CPLUSPLUS23 (999999L) /*TBD*/

#define REXLIB_HAS_CPP11 (REXLIB_CPLUSPLUS >= REXLIB_CPLUSPLUS11)
#define REXLIB_HAS_CPP14 (REXLIB_CPLUSPLUS >= REXLIB_CPLUSPLUS14)
#define REXLIB_HAS_CPP17 (REXLIB_CPLUSPLUS >= REXLIB_CPLUSPLUS17)
#define REXLIB_HAS_CPP20 (REXLIB_CPLUSPLUS >= REXLIB_CPLUSPLUS20)
#define REXLIB_HAS_CPP23 (REXLIB_CPLUSPLUS >= REXLIB_CPLUSPLUS23)
