// SPDX-License-Identifier: GPL-3.0-only

#ifndef REXLIB_SMALL_AXIS_COUNT
	#define REXLIB_SMALL_AXIS_COUNT 8UL
#endif

#ifndef REXLIB_SMALL_OPERAND_COUNT
	#define REXLIB_SMALL_OPERAND_COUNT 8UL
#endif

#ifndef REXLIB_SMALL_QUEUE_COUNT
	#define REXLIB_SMALL_QUEUE_COUNT 16UL
#endif

#ifndef REXLIB_SMALL_OUTPUT_OPERAND_COUNT
	#define REXLIB_SMALL_OUTPUT_OPERAND_COUNT 4UL
#endif

#ifndef REXLIB_SMALL_INPUT_OPERAND_COUNT
	#define REXLIB_SMALL_INPUT_OPERAND_COUNT 16UL
#endif

#ifndef REXLIB_SMALL_SCRATCH_OPERAND_COUNT
	#define REXLIB_SMALL_SCRATCH_OPERAND_COUNT 2UL
#endif

#ifndef REXLIB_DEFAULT_OPERATION_PROGRAM_CACHE_CAPACITY
	#define REXLIB_DEFAULT_OPERATION_PROGRAM_CACHE_CAPACITY 256UL
#endif
